version: "3.8"

services:
  celery:
    build:
      context: .
    volumes:
      - .:/myproject
    command: celery -A app.celery worker --loglevel=info

  flask:
    build:
      context: .
    volumes:
      - .:/myproject
    command: python app.py
    ports:
      - 5022:5022
    depends_on:
      - celery
